language: node_js
node_js:
  - "10"
  - "8"
notifications:
  recipients:
    - piro.outsider.reflex@gmail.com
before_script:
  - cd webextensions
  - npm install
  - make update_extlib
  - make install_extlib
script:
  - make lint
before_deploy:
  - make
deploy:
  provider: releases
  api_key:
    secure: "CbEH6VHAw3uWLKV/iNdtN4IHo66GjrtfhQnPm9EKvTUFLpDZZq2YUzSVs5MmKBZrkv3s8Kg/W0gyEYjejPODXCKZl5CX7AC6dpKoirunUhp47Xv3vxE1y7ehpDmnRF+Os8E7sDtwhF+R9zV9XBA1R6PytG1Rk3cUTACogyE80c8="
  file:
    - secondsearch-we.xpi
  skip_cleanup: true
  on:
    repo: piroor/secondsearch
    tags: true
